name: CI
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
      - name: Start up emulators
        run: docker compose up -d 
      - name: Restore cli build
        id: restore-cli-build
        uses: actions/cache/restore@v4
        with:
          path: ./.bin
          key: cli-build
      - run: ls -la && ls -la .bin # for test    
      - run: ./test.sh
    - name: Save cli build
      id: cache-cli-build
      uses: actions/cache/save@v4
      with:
        path: ./.bin
        key: cli-build