name: CI
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          power: true
      - name: Start up emulators
        run: docker compose up -d 
      - run: sbt test
